name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - run: npm i -g npm@8
    - run: npm ci
    - run: npm run lint

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        eslint-version:
          - 7
          - 8
        node-version:
          - 12
          - 14
          - 16
          - 18

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - run: npm i -g npm@8
    - run: npm ci
    - run: npm i eslint@${{ matrix.eslint-version }}
    - run: npm test
